
name: Causal Platform CI
pool: resilience-build-agents-1es

trigger:
  batch: true
  branches:
    include:
      - main

variables:
  NODE_VERSION: '16.x'
  YARN_CACHE_FOLDER: $(Pipeline.Workspace)/.yarn/cache
  isMainBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/main')]
  isProdBranch: $[eq(variables['Build.SourceBranch'], 'refs/heads/prod')]

stages:
  - stage: Compliance
    dependsOn: []
    jobs:
      - job: ComplianceJob
        pool:
          vmImage: windows-latest
        steps:
          - task: CredScan@3
            inputs:
              outputFormat: sarif
              debugMode: false

          - task: ComponentGovernanceComponentDetection@0
            inputs:
              scanType: 'Register'
              verbosity: 'Verbose'
              alertWarningLevel: 'High'

          - task: PublishSecurityAnalysisLogs@3
            inputs:
              ArtifactName: 'CodeAnalysisLogs'
              ArtifactType: 'Container'


  - stage: DeployProdBuildFrontendImages
    displayName: Prod Deploy - Frontend Images
    dependsOn: []
    # change to isProdBranch
    condition: and(eq(variables.enableDeploy, 'true'), eq(variables.isMainBranch, 'true'))
    jobs:
    - template: jobs/cd-frontend.yml
      parameters:
        name: "DeployProdBuildFrontendImagesJob"
        subscription: "$(subscription)"
        containerRegistry: "$(prod-container-registry)"

  - stage: DeployProdBuildBackendImages
    displayName: Prod Deploy - Backend Images
    dependsOn: []
    # change to isProdBranch
    condition: and(eq(variables.enableDeploy, 'true'), eq(variables.isMainBranch, 'true'))
    jobs:
    - template: jobs/cd-backend.yml
      parameters:
        name: "DeployProdBuildBackendImagesJob"
        subscription: "$(subscription)"
        containerRegistry: "$(prod-container-registry)"

  - stage: DeployProdHelmCharts
    displayName: Deploy Prod Helm Charts
    dependsOn:
      - DeployProdBuildFrontendImages
      - DeployProdBuildBackendImages
    # change to isProdBranch
    condition: and(eq(variables.enableDeploy, 'true'), and(succeeded(), eq(variables.isMainBranch, 'true')))
    jobs:
      - template: jobs/cd-helm.yml
        parameters:
          name: "DeployProdHelmChartsJob"
          subscription: "$(subscription)"
          aksClusterName: "$(prod-aks-cluster-name)"
          aksResourceGroup: "$(prod-aks-resource-group)"
          valueFile: "config/helm/causal-services/values.prod.yaml"