changesetIgnorePatterns:
  - "**/*.spec.{js,ts,tsx}"

npmAuthToken: "${NPM_AUTH_TOKEN-emptytoken}"

packageExtensions:
  3d-force-graph-ar@*:
    peerDependencies:
      three: "*"
  3d-force-graph-vr@*:
    peerDependencies:
      three: "*"
  "@fluentui/font-icons-mdl2@*":
    peerDependencies:
      react: "*"
  "@fluentui/style-utilities@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@uifabric/icons@*":
    peerDependencies:
      react: "*"
  "@uifabric/styling@*":
    peerDependencies:
      "@types/react-dom": "*"
      react: "*"
      react-dom: "*"
  aframe-forcegraph-component@*:
    peerDependencies:
      three: "*"
  elkjs@*:
    peerDependencies:
      web-worker: "*"
  react-force-graph@*:
    peerDependencies:
      three: "*"
  "@datashaper/app-framework@*":
    peerDependencies:
      '@thematic/react': "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.2.4.cjs
