name: Build Frontend Container
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'javascript/**/*'
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.js'
      - '**/*.mjs'
      - '**/*.cjs'
      - '**/*.json'
      - .github/workflows/container-frontend.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: yarn install
        name: Install Webapp Dependencies

      - run: yarn build
        name: Build Webapp

      - name: Get Docker Image Details
        id: image-details
        run: |
          echo "Get Details; Ref=$REF, Run Number=$RUN_NUM"
          if [ "$REF" == "refs/heads/main" ]; then
              echo "tag=latest" >>$GITHUB_OUTPUT
          else
              echo "tag=dev-$RUN_NUM" >>$GITHUB_OUTPUT
          fi
        env:
          REF: ${{ github.ref }}
          RUN_NUM: ${{ github.run_number }}

      - name: Build and Publish Docker Container
        uses: pmorelli92/github-container-registry-build-push@2.0.0
        if: github.ref == 'refs/heads/main'
        with:
          github-push-secret: ${{secrets.GITHUB_TOKEN}}
          docker-image-name: showwhy-frontend
          docker-image-tag:  ${{ steps.image-details.outputs.tag }}
          dockerfile-path: ./javascript/webapp/Dockerfile
          build-context: ./javascript/webapp

      - name: Build Docker Container (dev)
        if: github.ref != 'refs/heads/main'
        working-directory: ./javascript/webapp
        run: docker build .
  