name: Build Backend Container
on:
  push:
    branches: [main]
  pull_request:
    paths:
      - 'python/**/*'
      - '**/*.py'
      - '**/*.toml'
      - .github/workflows/container-backend.yml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Build Backend Image
        working-directory: ./python/backend
        run: docker build . -t ghcr.io/microsoft9/showwhy-backend:latest

      - name: 'Push to GitHub Container Registry'
        if: github.ref == 'refs/heads/main'
        run: docker push ghcr.io/microsoft9/showwhy-backend:latest
